[build]
  command = "# no build command"
  functions = "netlify/functions"
  publish = "public"

[dev]
  functions = "netlify/functions"
  publish = "public"

  [functions]
  included_files = ["*.yaml"]